### ISSUE TITLE
Dive into a problem domain

### ISSUE THREAD

**Issue by iradche** [IPMITMO/robotic-computer-vision-system#2]
- [x] Find and study Open Source analogs 
- [x] Find and study mathematical models of kinematic system
- [x]  Find commercial analogs

**Comment by Nazukin-Dmitry** [comment]
Object recognition:
https://www.tensorflow.org/versions/r0.11/tutorials/image_recognition/index.html
https://github.com/BVLC/caffe/wiki/Model-Zoo

**Comment by Nazukin-Dmitry** [comment]
Object detection:
https://github.com/thtrieu/yolotf (tensorflow implementation of http://pjreddie.com/darknet/yolo/)
https://github.com/Russell91/TensorBox
